# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run main.py

on:
  schedule:
    - cron: '30 14 * * *'

permissions:
  contents: read

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v4

      - name: instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: instalar as dependencias
        run: python -m pip install -r requirements.txt
      
      - name: executar arquivo
        run: python main.py
